name: Deploy Python App (Self-hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Stop existing Python process (if running)
        run: |
          pkill -f "python main.py" || true
        continue-on-error: true

      - name: Wait for process to stop
        run: sleep 2

      - name: Start Python application
        run: |
          nohup python main.py > app.log 2>&1 &
          echo $! > app.pid
          echo "Application started with PID: $(cat app.pid)"

      - name: Verify application is running
        run: |
          sleep 5
          if ps -p $(cat app.pid) > /dev/null; then
            echo "Application is running successfully"
          else
            echo "Application failed to start"
            cat app.log
            exit 1
          fi

      - name: Show application logs
        run: |
          echo "=== Application Logs ==="
          tail -20 app.log
